before_script:
- bash test/docker_install.sh > /dev/null
- cp test/misc/redis.conf /usr/local/etc/redis/redis.conf

# Test PHP 7.0
test:7.0:
  image: php:7.0
  script:
  - phpunit --configuration phpunit.xml.dist

# Test PHP 7.2
test:7.1:
  image: php:7.1
  script:
  - phpunit --configuration phpunit.xml.dist

# Test PHP 7.2
test:7.2:
  image: php:7.2
  script:
  - phpunit --configuration phpunit.xml.dist
