pipeline:
  lint:
    image: php:8.1-cli
    commands:
      - apt update && apt install -y wget unzip git
      - wget https://getcomposer.org/download/latest-stable/composer.phar
      - php composer.phar install --dev
      - php -d memory_limit=256M vendor/bin/phpcs -s --standard=ruleset.xml
