matrix:
  PHP_VERSION:
    - 7.4
    - 8.0
    - 8.1
    - 8.2

pipeline:
  unit-tests:
    image: php:${PHP_VERSION}-cli
    commands:  
      - apt-get update -yq
      - apt-get install git wget procps unzip -y
      - pecl install -o -f redis && rm -rf /tmp/pear
      - docker-php-ext-enable redis
      - docker-php-ext-install pcntl
      - wget https://getcomposer.org/download/latest-stable/composer.phar
      - php composer.phar install --dev
      - php vendor/bin/phpunit --verbose --configuration phpunit.xml

services:
  redis:
    image: redis:7

depends_on:
  - lint